[build]
rustflags = [
    "-D",
    "unused_must_use",
    "-D",
    "clippy::panic",
    "-D",
    "clippy::unwrap_used",
    "-D",
    "clippy::expect_used",
    "-A",
    "clippy::single_match",
]
